#! /usr/bin/env ruby
# because rubygems shims assume a gem's executables are Ruby

require "rubygems"
require "shellwords"

platform_string = RbConfig::CONFIG['arch']

exe_path =
  case platform_string
  when /darwin\z/     then File.join(__dir__, "darwin/sass")
  when /linux/        then File.join(__dir__, "#{platform_string}/sass")
  when /mingw32\z/    then File.join(__dir__, "mingw32/sass.bat")
  else
    STDERR.puts(<<~ERRMSG)
      ERROR: dartsass-ruby does not support the #{platform_string} platform
    ERRMSG
    exit 1
  end

command = Shellwords.join([ exe_path, ARGV ].flatten)
puts "+ #{command}"
exec(command)
